Repository Codeit-Sprint-6-Part4-Team15/Epigram, pull requests merged in 2024-08, with the labels that each got.

#12 Feat/epi 30/chart : ChartContainer, DonutChart
  .env
  package-lock.json
  package.json
  public/assets/emoji-heart.svg
  public/assets/emoji-mad.svg
  public/assets/emoji-sad.svg
  public/assets/emoji-smile.svg
  public/assets/emoji-worry.svg
  public/assets/emotionChart/ic_emoji-heart.svg
  public/assets/emotionChart/ic_emoji-mad.svg
  public/assets/emotionChart/ic_emoji-sad.svg
  public/assets/emotionChart/ic_emoji-smile.svg
  public/assets/emotionChart/ic_emoji-worry.svg
  public/assets/emotionChart/index.ts
  src/app/api/axios.ts
  src/app/mypage/page.tsx
  src/app/page.tsx
  src/components/ChartContainer.tsx
  src/components/DonutChart.tsx
  src/styles.css
  src/types.ts
  tailwind.config.ts
Labels: enhancement

#10 Feat/epi 5/modal : useModal hook, Modal, ConfirmModal + ProfileModal
  public/assets/border_note.png
  public/assets/border_note.svg
  public/assets/ic_close.svg
  public/assets/ic_notice.svg
  public/assets/ic_user.svg
  src/app/layout.tsx
  src/app/test/page.tsx
  src/components/commons/Button.tsx
  src/components/commons/Comments.tsx
  src/components/commons/Modal/ConfirmModal.tsx
  src/components/commons/Modal/Modal.tsx
  src/components/commons/Modal/ProfileModal.tsx
  src/components/commons/TextArea.tsx
  src/hooks/useModal.tsx
  src/type.ts
  tailwind.config.ts
Labels: enhancement

#20 Feat/epi 35/recent comments
  .eslintrc.js
  .prettierrc.js
  .vscode/setting.json
  README.md
  package-lock.json
  package.json
  public/assets/emotionChart/index.ts
  public/assets/ic_error.svg
  public/assets/ic_plus.svg
  src/app/api/axios.ts
  src/app/api/comment.ts
  src/app/epigrams/page.tsx
  src/app/globals.css
  src/app/layout.tsx
  src/app/mypage/page.tsx
  src/app/page.tsx
  src/app/test/page.tsx
  src/components/ChartContainer.tsx
  src/components/CommentContainer.tsx
  src/components/DonutChart.tsx
  src/components/EmotionCalender.tsx
  src/components/LoadingError.tsx
  src/components/commons/Button.tsx
  src/components/commons/Comment.tsx
  src/components/commons/Comments.tsx
  src/components/commons/Dropdown.tsx
  src/components/commons/Loader.tsx
  src/components/commons/Modal/ConfirmModal.tsx
  src/components/commons/Modal/Modal.tsx
  src/components/commons/Modal/ProfileModal.tsx
  src/components/commons/RadioGroup.tsx
  src/components/commons/TextArea.tsx
  src/components/commons/TextCard.tsx
  src/components/commons/Toggle.tsx
  src/hooks/useDetectClose.tsx
  src/hooks/useModal.tsx
  src/hooks/useScrollAnimation.tsx
  src/styles.css
  tailwind.config.ts
  tsconfig.json
Labels: enhancement

#27 Feat/EPI-10/SignUpPage
  public/assets/authPage/logo_epigram.svg
  public/assets/authPage/logo_google.svg
  public/assets/authPage/logo_kakao.svg
  src/app/(auth)/layout.tsx
  src/app/(auth)/signin/page.tsx
  src/app/(auth)/signup/page.tsx
  src/app/api/auth.ts
  src/components/commons/Button.tsx
  src/components/commons/Input.tsx
  src/components/commons/InputError.tsx
  src/types/auth.d.ts
Labels: enhancement

#38 Fix/epi 47/deployment fix
  next.config.mjs
  src/app/(withWidget)/epigrams/[id]/page.tsx
  src/app/api/comment.ts
  src/app/api/user.ts
  src/components/EpigramDetailPageCommentsSection.tsx
  src/components/commons/Comment.tsx
  src/components/commons/Input.tsx
  src/types/user.d.ts
Labels: 📌 확인 요청

#39 fix: type누락 및 EpigramsContainer 추가오류 해결
  src/app/(withWidget)/epigrams/[id]/page.tsx
  src/components/EpigramsContainer.tsx
  src/types/epigrams.d.ts
Labels: 📌 확인 요청

#35 feat: 텍스트카드 hightclass프롭스 추가, 말줄임 추가
  src/components/commons/TextCard.tsx
Labels: enhancement, ✨ 작업 완료

#40 Refactor/my page : 오류 수정
  public/assets/ic_camera.svg
  src/app/(withWidget)/epigrams/page.tsx
  src/app/(withWidget)/mypage/page.tsx
  src/app/api/axios.ts
  src/components/ChartContainer.tsx
  src/components/DonutChart.tsx
  src/components/EpigramsContainer.tsx
  src/components/FloatingButtons.tsx
  src/components/TodayEpigram.tsx
  src/components/UserInfo.tsx
  src/types/epigrams.d.ts
Labels: ✨ 작업 완료

#43 Feat/epi 52/SWR 전역설정
  package-lock.json
  package.json
  src/app/(withWidget)/mypage/page.tsx
  src/app/_app.tsx
  src/app/mypage/page.tsx
  src/components/EmotionCalender.css
  src/components/commons/TodayEmotionSelector.tsx
Labels: 📌 확인 요청

#47 Fix/epi 47/deployment fix; mypage, search 빌드 오류 수정, 테스트페이지 제거
  package-lock.json
  package.json
  src/app/search/page.tsx
  src/app/test/login.tsx
  src/app/test/page.tsx
  src/app/test/token.ts
  src/components/ChartContainer.tsx
  src/components/commons/Comment.tsx
Labels: 📌 확인 요청, ✨ 작업 완료

#44 Feat/epi 54/not found
  package-lock.json
  package.json
  src/app/not-found.tsx
Labels: ✨ 작업 완료

#48 Feat/epi 30/chart : 차트 오류 수정
  .eslintrc.js
  package-lock.json
  public/assets/emoji-heart.svg
  public/assets/emoji-mad.svg
  public/assets/emoji-sad.svg
  public/assets/emoji-smile.svg
  public/assets/emoji-worry.svg
  src/app/globals.css
  src/app/page.tsx
  src/components/ChartContainer.tsx
  src/components/DonutChart.tsx
Labels: ✨ 작업 완료

#33 Feat/epi 39/에피그램 메인페이지 피드
  .vscode/setting.json
  next.config.mjs
  package-lock.json
  src/app/feed/page.tsx
  src/components/FloatingButtons.tsx
  src/components/commons/TextArea.tsx
Labels: ✨ 작업 완료

#45 Feat/epi 49/에피그램 수정
  public/assets/logo.svg
  src/app/(withWidget)/epigrams/[id]/edit/page.tsx
  src/app/(withWidget)/epigrams/[id]/page.tsx
  src/app/Header.tsx
  src/app/addepigram/page.tsx
  src/app/api/axios.ts
  src/app/globals.css
  src/app/mypage/page.tsx
  src/app/page.tsx
  src/app/search/page.tsx
  src/components/commons/DropdownMenu.tsx
  src/components/commons/Modal/Modal.tsx
  src/types/epigrams.d.ts
Labels: 📌 확인 요청, ✨ 작업 완료

#51 Feat/epi 44/detail page comments
  next.config.mjs
  src/app/(withWidget)/epigrams/[id]/page.tsx
  src/app/api/comment.ts
  src/app/mypage/page.tsx
  src/app/search/page.tsx
  src/components/EpigramDetailPageCommentsSection.tsx
  src/components/commons/Comment.tsx
  src/components/commons/TextArea.tsx
  src/components/commons/Toggle.tsx
Labels: 📌 확인 요청, ✨ 작업 완료

#52 feat: 헤더 컴포넌트 및 axios 수정 및 로그아웃 기능
  package-lock.json
  src/app/Header.tsx
  src/app/api/axios.ts
  src/components/UserInfo.tsx
Labels: 📌 확인 요청

#53 fix: 빌드오류 수정 및 폴더정리, 랜딩페이지 시작하기 버튼 오류 수정
  src/app/(withWidget)/epigrams/[id]/page.tsx
  src/app/(withWidget)/epigrams/page.tsx
  src/app/(withWidget)/layout.tsx
  src/app/(withWidget)/mypage/page.tsx
  src/app/api/comment.ts
  src/app/feed/page.tsx
  src/app/page.tsx
  src/app/search/page.tsx
  src/components/commons/Comment.tsx
  src/components/commons/LoadingError.tsx
  src/components/commons/TodayEmotionSelector.tsx
  src/components/epigrams/EpigramDetailPageCommentsSection.tsx
  src/components/epigrams/EpigramsContainer.tsx
  src/components/epigrams/FloatingButtons.tsx
  src/components/epigrams/TodayEpigram.tsx
  src/components/myPage/ChartContainer.tsx
  src/components/myPage/CommentContainer.tsx
  src/components/myPage/DonutChart.tsx
  src/components/myPage/EmotionCalender.css
  src/components/myPage/EmotionCalender.tsx
  src/components/myPage/MyContents.tsx
  src/components/myPage/UserInfo.tsx
  src/types.ts
  src/types/types.d.ts
Labels: ✨ 작업 완료

#55 fix: 빌드오류수정, 댓글 작성시 바로 보이게
  next.config.mjs
  src/components/epigrams/EpigramDetailPageCommentsSection.tsx
Labels: ✨ 작업 완료

#60 feat: 오늘의 감정 선택 시 달력과 차트 리랜더링, 달력 현재달로 돌아가는 버튼, 달력 년월 프롭스설정
  public/assets/emoji-heart.svg
  public/assets/emoji-mad.svg
  public/assets/emoji-sad.svg
  public/assets/emoji-smile.svg
  public/assets/emoji-worry.svg
  src/app/(withWidget)/mypage/page.tsx
  src/components/commons/TodayEmotionSelector.tsx
  src/components/myPage/EmotionCalender.tsx
Labels: ✨ 작업 완료

#64 feat: 오늘의감정 epigrams페이지에서 미로그인시 토스트 출력, 클라이언트사이드로 userId가져오기 구현
  src/app/(withWidget)/epigrams/page.tsx
  src/components/commons/TodayEmotionSelector.tsx
  src/components/epigrams/ClientSideUserId.tsx
Labels: ✨ 작업 완료

#66 Feat 헤더 ui 변경, 검색 페이지 초기 데이터 삭제
  src/app/Header.tsx
  src/app/search/components/EmptyEpigram.tsx
  src/app/search/components/SearchEpigram.tsx
  src/app/search/page.tsx
  src/components/commons/DropdownMenu.tsx
  tailwind.config.ts
Labels: 📌 확인 요청

#65 feat: 오늘의감정 첫클릭시 토스트경고(1회), 랜딩페이지 시작버튼 클릭시 apigrams페이지 이동
  src/app/page.tsx
  src/components/commons/TodayEmotionSelector.tsx
Labels: ✨ 작업 완료

#67 Feat/epi 58/로그인, 회원가입 페이지 UI 디테일 및 오류 수정
  src/app/(auth)/layout.tsx
  src/app/(auth)/signin/page.tsx
  src/app/(auth)/signup/page.tsx
  src/app/Header.tsx
  src/components/commons/Input.tsx
  src/components/commons/InputError.tsx
  src/types.ts
  tailwind.config.ts
Labels: 📌 확인 요청, ✨ 작업 완료

#69 Refactor/epi 60/상세페이지, 작성페이지, 피드 페이지 수정
  src/app/(withWidget)/epigrams/[id]/page.tsx
  src/app/addepigram/page.tsx
  src/app/feed/page.tsx
  src/app/globals.css
  src/app/loading.tsx
  src/components/epigrams/FloatingButtons.tsx
Labels: 📌 확인 요청, ✨ 작업 완료

#70 Feat/epi 59/epigrams, mypage 모바일 화면 넘침 수정
  src/app/(withWidget)/epigrams/page.tsx
  src/app/(withWidget)/mypage/page.tsx
  src/app/page.tsx
Labels: ✨ 작업 완료

#71 Feat/epi 61/에피그램 링크 드롭다운 메뉴 추가
  public/assets/ic-copy.svg
  src/app/(withWidget)/epigrams/[id]/page.tsx
  src/app/(withWidget)/epigrams/page.tsx
  src/app/addepigram/page.tsx
  src/app/feed/page.tsx
  src/app/page.tsx
  src/components/commons/DropdownMenu.tsx
Labels: ✨ 작업 완료

#74 feat: 미로그인시 댓글창 로그인유도, 로그인시 이전페이지 보기
  src/app/(auth)/signin/page.tsx
  src/components/epigrams/EpigramDetailPageCommentsSection.tsx
Labels: ✨ 작업 완료

#77 fix: 피드 화면에 너무 꽉차지 않게 맥스 700 설정, 아이패드 프로 1024*1366에서 그리드가 벌어져있는것 수정
  src/app/feed/page.tsx
Labels: 📌 확인 요청, ✨ 작업 완료

#79 feat: epigram 태그 없을 때 수정, 스타일 추가
  src/app/Header.tsx
  src/app/search/components/SearchEpigram.tsx
Labels: 📌 확인 요청

#82 Fix/epi 57/헤더 서버사이드로 빠르게 랜더링
  src/app/(auth)/signin/page.tsx
  src/app/(auth)/signup/page.tsx
  src/app/Header.tsx
  src/components/Header/HeaderClient.tsx
  src/components/Header/HeaderServer.tsx
Labels: 📌 확인 요청, ✨ 작업 완료

#83 fix: 헤더 로고 클릭시 홈으로
  src/components/Header/HeaderClient.tsx
  src/components/Header/HeaderServer.tsx
Labels: 📌 확인 요청, ✨ 작업 완료

#86 Fix/epi 57/오늘의 감정 토스트 삭제, 상세페이지 댓글 수정, 삭제 랜더링, 댓글 갯수 랜더링, 더보기 제거
  src/app/api/comment.ts
  src/components/commons/TodayEmotionSelector.tsx
  src/components/epigrams/EpigramDetailPageCommentsSection.tsx
Labels: ✨ 작업 완료

#87 Feat/epi 55/스타일, 사이드바, 새로 고침 추가
  src/components/Header/HeaderClient.tsx
  src/components/Header/HeaderServer.tsx
  src/components/commons/Modal/ProfileEditModal.tsx
Labels: 📌 확인 요청
